### ISSUE TITLE
`CollisionFlagMap` should be an interface & publish new pathfinder version please

### ISSUE THREAD

**Issue by Jire** [rsmod/rsmod#26]
`CollisionFlagMap` should be an interface as `flags` should not need to be exposed, this way API consumers can implement their own flag map from their existing flags if they chose.

**Comment by Tomm0017** [comment]
This is something I did weigh as an option. The issue is the performance hit from vtable lookup. `CollisionFlagMap.get` is one of the hottest code paths. Allowing abstractions would deal a heavy hit, when we can instead just provide a generic `CollisionFlagMap` to be used by consumers.
