### ISSUE TITLE
Cache Index CRCs verification during login logic allows bypassing

### ISSUE THREAD

**Issue by bmyte** [rsmod/rsmod#6]
https://github.com/rsmod/rsmod/blob/43d42a54601ac2b2e94318c6252c2cd70ba64dc3/plugins/api/src/main/kotlin/org/rsmod/plugins/api/protocol/codec/login/LoginDecoder.kt#L249

Kyle E pointed this out to me last night so I don't know if he brought it to your attention or not, but I do believe CRCs can be negative and while the check if greater than 0 allows for not checking index 16 (as it is 0) means any client could write all CRCs as zero or negative and completely bypass the verification no?

I would submit that the greater than zero check adds more overhead than to simply just check that index 16 is 0 like it should be (20 checks if the value is greater than zero as opposed to just a single check for each CRC received matching).

These are the CRC that the 193 client sent as proof they can be negative (note this is printed client side - not after being read/after being written etc):
[-1173228978, -1157589397, -1212584219, -570258262, 1319113061, 268483285, 187074646, -353829414, -1052908534, -1247884930, -597431892, -608311250, -274006329, -1116086727, 153718440, -445574398, 0, -1481854411, -2029010792, 342059222, 2108672106]

In rsmod1 I use the RL cache libs to retrieve the CRCs as so: 
val crcs = filestore.indexes.map { it.crc }.toIntArray()

And that resulted in matching CRCs just fine for me. While CRCs themselves are not inherently signed, the int data type of the variable they are residing in within the client is inherently signed and if you read using the same encoding the client sends then you should also be looking at negative values server side.

The attached code snippet should sufficiently verify CRCs for you barring all the above is true:
[patch.txt](https://github.com/rsmod/rsmod/files/6676870/patch.txt)

**Comment by Tomm0017** [comment]
Addressed in commit https://github.com/rsmod/rsmod/commit/089dede92254ed70d828e2c4d18cf2d5441b3f2a
